import { useState } from 'react';
import { X } from 'lucide-react';
import { TEST_TYPE_LABELS } from "./types";

const SERVICE_TYPES = ['Material Testing', 'Calibration', 'Both'];
const STATUSES = ['Pending', 'Ongoing', 'Completed', 'Cancelled'];
const REQUEST_FORMS = ['Signed', 'Waiting', 'N/A'];

// Helper to format date to YYYY-MM-DD (from AddClientModalJ)
const formatDateForInput = (dateValue) => {
  if (!dateValue) return '';
  try {
    const date = new Date(dateValue);
    if (!isNaN(date.getTime())) {
      return date.toISOString().split('T')[0];
    }
  } catch (e) {
    return '';
  }
  return '';
};

export function AddClientModal({ isOpen, onClose, onAdd }) {
  // Move testTypes useState inside the component (from AddClientModalE)
  const [testTypes, setTestTypes] = useState(['FTIR', 'CT', 'CTT', 'MO', 'HT', 'FT', 'TS', 'BT', 'RE', 'UC', 'FD', 'NTA', 'O']);

  const [categories, setCategories] = useState([
    'BatStateU College',
    'Private HEIs',
    'Industry',
    'Private Individual',
    'Senior High',
    'BatStateU IS',
  ]);

  // DECLARATION FOR ADDING NEW CATEGORY
  const [isAdding, setIsAdding] = useState(false);
  const [newcat, setNewCat] = useState({ name: '', color: '#06b6d4' });
  const [isAddingNewType, setIsAddingNewType] = useState(false);
  const [newTypeInput, setNewTypeInput] = useState('');

  // DECLARATION FOR CALENDAR DATES
  const today = new Date().toISOString().split('T')[0];
  const handleDateChange = (field, value) => {
    if (value > today) {
      setFormData(prev => ({ ...prev, [field]: '' }));
    } else {
      setFormData(prev => ({ ...prev, [field]: value }));
    }
  }

  const [formData, setFormData] = useState({
    // Note: id, serviceNo, serviceRequestID should be auto-generated by backend
    
    // Client Information
    name: '',
    address: '',
    email: '',
    phone: '',
    
    // Service Details
    category: 'Industry',
    serviceType: 'Material Testing',
    status: 'Pending',
    progress: 0,
    
    // Dates
    dateRequested: new Date().toISOString().split('T')[0],
    startDate: new Date().toISOString().split('T')[0],
    dueDate: new Date().toISOString().split('T')[0],
    dateReleased: '',
    dateClaimed: '',
    testDate: '',
    releasedROA: '',
    
    // Documentation & Forms
    requestForm: 'Waiting',
    reportAnalysis: false, // Keeping the name from E but will map to 'roa' for backend
    
    // Sample Information
    sampleNo: '',
    specimenNo: '',
    sampleCount: 0,
    
    // Financial
    amount: 0,
    officialReceipt: false,
    
    // Test Types & Remarks
    testTypes: [],
    remarks: '',
  });

  const handleAddNewType = () => {
    if (newTypeInput.trim() && !testTypes.includes(newTypeInput.trim().toUpperCase())) {
      const newType = newTypeInput.trim().toUpperCase();
      setTestTypes([...testTypes, newType]);
      setNewTypeInput('');
      setIsAddingNewType(false);
      // Save to backend/database here
      // Example: saveTestTypeToBackend(newType);
    }
  };
  
  // SUBMIT HANDLER WITH DATA TRANSFORMATION (from AddClientModalJ)
  const handleSubmit = (e) => {
    e.preventDefault();

    // Validation
    if (!formData.dateRequested) {
      alert("Date Requested is required");
      return;
    }
    
    if (new Date(formData.dateRequested) > new Date()) {  
      alert("Date Requested cannot be in the future");
      return;
    }
    
    // Transform data to match database schema
    const dataForBackend = {
      // Backend should auto-generate: id, serviceNo, serviceRequestID
      
      // Client Information
      name: formData.name.trim(),
      address: formData.address.trim(),
      email: formData.email.trim().toLowerCase(),
      phone: formData.phone.replace(/\s/g, ''), // Remove formatting spaces
      
      // Service Details
      category: formData.category,
      serviceType: formData.serviceType,
      status: formData.status,
      progress: Number(formData.progress),
      
      // Dates (ensure YYYY-MM-DD format, or null if empty)
      dateRequested: formatDateForInput(formData.dateRequested),
      startDate: formatDateForInput(formData.startDate),
      dueDate: formatDateForInput(formData.dueDate),
      dateReleased: formatDateForInput(formData.dateReleased) || null,
      dateClaimed: formatDateForInput(formData.dateClaimed) || null,
      testDate: formatDateForInput(formData.testDate) || null,
      releasedROA: formatDateForInput(formData.releasedROA) || null,
      
      // Documentation
      requestForm: formData.requestForm,
      roa: formData.reportAnalysis, // Map reportAnalysis to roa for backend
      
      // Sample Information
      sampleNo: formData.sampleNo.trim() || null,
      specimenNo: formData.specimenNo.trim() || null,
      sampleCount: Number(formData.sampleCount) || 0,
      
      // Financial
      amount: Number(formData.amount),
      officialReceipt: formData.officialReceipt,
      
      // Test Types (convert array to comma-separated string)
      testTypes: formData.testTypes.join(', '),
      
      // Additional
      remarks: formData.remarks.trim() || null,
    };
    
    // Send to backend
    onAdd(dataForBackend);
    
    // Reset form
    setFormData({
      name: '',
      address: '',
      email: '',
      phone: '',
      category: 'Industry',
      serviceType: 'Material Testing',
      status: 'Pending',
      progress: 0,
      dateRequested: new Date().toISOString().split('T')[0],
      startDate: new Date().toISOString().split('T')[0],
      dueDate: new Date().toISOString().split('T')[0],
      dateReleased: '',
      dateClaimed: '',
      testDate: '',
      releasedROA: '',
      requestForm: 'Waiting',
      reportAnalysis: false,
      sampleNo: '',
      specimenNo: '',
      sampleCount: 0,
      amount: 0,
      officialReceipt: false,
      testTypes: [],
      remarks: '',
    });
  };

  const toggleTestType = (type) => {
    setFormData(prev => ({
      ...prev,
      testTypes: prev.testTypes.includes(type)
        ? prev.testTypes.filter(t => t !== type)
        : [...prev.testTypes, type],
    }));
  };

  if (!isOpen) return null;
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl bg-gradient-to-br from-slate-900 to-slate-800 border border-white/10 shadow-2xl">
        <div className="sticky top-0 z-10 flex items-center justify-between p-6 border-b border-white/10 bg-slate-900/95 backdrop-blur-xl">
          <h2 className="text-2xl font-bold text-white">Add New Client</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-lg bg-red-500/20 text-red-300 hover:bg-red-500/30 border border-red-500/30 hover:border-red-500/50 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/*ALL CLIENT INFORMATION IS EDITED UP TO LINE 167*/}
        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Client Info Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Client Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Client Name <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => {
                    const value=e.target.value;
                    const regex=/[^a-zA-Z.'()-\s]/g;
                    const onlyLetters=value.replace(regex, "");
                    setFormData({...formData, name: onlyLetters});
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="Enter client name"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Address <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  required
                  value={formData.address}
                  onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="Enter address"
                />
              </div>
            </div>
          </div>

          {/*ALL CONTACT INFORMATION IS EDITED UP TO LINE 208*/}
          {/* Contact Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Contact Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Email <span className="text-red-500">*</span></label>
                <input
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="email@example.com"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Phone <span className="text-red-500">*</span></label>
                <input
                  type="tel"
                  required
                  value={formData.phone}
                  onChange={(e) => {
                    const value = e.target.value;
                    const regex = /[^0-9+\-() ]/g;
                    const formattedPhone = value.replace(regex, "");
                    setFormData({ ...formData, phone: formattedPhone });
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="+63 123 456 7890"
                />
              </div>
            </div>
          </div>

          {/* Service Details */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Service Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Category <span className="text-red-500">*</span></label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {categories.map((cat) => (
                    <option key={cat} value={cat} className="bg-slate-800">{cat}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Service Type <span className="text-red-500">*</span></label>
                <select
                  value={formData.serviceType}
                  onChange={(e) => setFormData({ ...formData, serviceType: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {SERVICE_TYPES.map((type) => (
                    <option key={type} value={type} className="bg-slate-800">{type}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Status <span className="text-red-500">*</span></label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {STATUSES.map((status) => (
                    <option key={status} value={status} className="bg-slate-800">{status}</option>
                  ))}
                </select>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Progress: {formData.progress}%</label>
              <input
                type="range"
                min="0"
                max="100"
                value={formData.progress}
                onChange={(e) => setFormData({ ...formData, progress: Number(e.target.value) })}
                className="w-full h-2 bg-white/10 rounded-lg appearance-none cursor-pointer accent-cyan-500"
              />
            </div>
          </div>

          {/* Dates Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Important Dates</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Requested <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  required
                  value={formData.dateRequested}
                  max={today}
                  onChange={(e) => handleDateChange('dateRequested', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Start Date <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  required
                  value={formData.startDate}
                  onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Due Date <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  required
                  value={formData.dueDate}
                  onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Claimed</label>
                <input
                  type="date"
                  value={formData.dateClaimed}
                  max={today}
                  onChange={(e) => handleDateChange('dateClaimed', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Released</label>
                <input
                  type="date"
                  value={formData.dateReleased}
                  max={today}
                  onChange={(e) => handleDateChange('dateReleased', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
            </div>
          </div>

          {/* Request Form and Amount */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Documentation & Payment</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Request Form Status <span className="text-red-500">*</span></label>
                <select
                  value={formData.requestForm}
                  onChange={(e) => setFormData({ ...formData, requestForm: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {REQUEST_FORMS.map((form) => (
                    <option key={form} value={form} className="bg-slate-800">{form}</option>
                  ))}
                </select>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date of Test</label>
                <input
                  type="date"
                  value={formData.testDate || ''}
                  onChange={(e) => setFormData({ ...formData, testDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Released of ROA Date</label>
                <input
                  type="date"
                  value={formData.releasedROA || ''}
                  onChange={(e) => setFormData({ ...formData, releasedROA: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{colorScheme: 'dark'}}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Report of Analysis</label>
                  <div className="p-2.5 bg-white/5 border border-white/10 rounded-lg">
                    <div className="flex items-center gap-3">
                      <input
                      type="checkbox"
                      id="reportAnalysis"
                      checked={formData.reportAnalysis || false}
                      onChange={(e) => setFormData({ ...formData, reportAnalysis: e.target.checked })}
                      className="w-5 h-5 rounded bg-white/5 border border-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    />
                    <label htmlFor="reportAnalysis" className="text-sm font-medium text-green-300">ROA Available</label>
                  </div>
                 </div> 
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Sample No.</label>
                <input
                  type="text"
                  value={formData.sampleNo || ''}
                  onChange={(e) => setFormData({ ...formData, sampleNo: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="e.g., S-001"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Specimen No.</label>
                <input
                  type="text"
                  value={formData.specimenNo || ''}
                  onChange={(e) => setFormData({ ...formData, specimenNo: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="e.g., SP-001"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Sample Count</label>
                <input
                  type="number"
                  min="0"
                  value={formData.sampleCount || ''}
                  onChange={(e) => setFormData({ ...formData, sampleCount: Number(e.target.value) || 0 })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="0"
                />
              </div>
            </div>
            
            {/*EDITED UP TO LINE 546*/}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Amount (₱) <span className="text-red-500">*</span></label>
                <input
                  type="number"
                  min="0"
                  required
                  value={formData.amount || ''}
                  onChange={(e) => setFormData({ ...formData, amount: Number(e.target.value) })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="0"
                />
              </div>
              <div> 
                <label className="block text-sm font-medium text-gray-300 mb-2">Official Receipt</label>
                  <div className="p-2.5 bg-white/5 border border-white/10 rounded-lg">
                    <div className="flex items-center gap-3">
                      <input
                      type="checkbox"
                      id="officialReceipt"
                      checked={formData.officialReceipt || false}
                      onChange={(e) => setFormData({ ...formData, officialReceipt: e.target.checked })}
                      className="w-5 h-5 rounded bg-white/5 border border-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    />
                    <label htmlFor="officialReceipt" className="text-sm font-medium text-green-300">Receipt Available</label>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Remarks</label>
              <textarea
                value={formData.remarks || ''}
                onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                placeholder="Additional notes or remarks"
                rows={3}
              />
            </div>
          </div>

          {/* Test Types */}
<div className="space-y-4">
  <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Test Types</h3>
  <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-2">
    {testTypes.map((type) => (
      <button
        key={type}
        type="button"
        onClick={() => toggleTestType(type)}
        className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${
          formData.testTypes.includes(type)
            ? 'bg-gradient-to-r from-pink-500 to-purple-600 text-white shadow-lg shadow-pink-500/50 border border-pink-500'
            : 'bg-white/5 text-gray-300 border border-white/10 hover:bg-white/10'
        }`}
        title={TEST_TYPE_LABELS[type]}
      >
        {type}
      </button>
    ))}
    
    {/* Add New Type Button/Input */}
    {isAddingNewType ? (
      <div className="col-span-3 flex items-center gap-2 p-2 bg-white/5 border border-cyan-500/50 rounded-lg">
        <input
          type="text"
          placeholder="Type code"
          value={newTypeInput}
          onChange={(e) => setNewTypeInput(e.target.value)}
          maxLength={4}
          className="flex-1 px-3 py-1.5 bg-slate-900 border border-white/20 rounded text-sm text-white focus:ring-1 focus:ring-cyan-500 outline-none uppercase"
          onKeyPress={(e) => {
            if (e.key === 'Enter') {
              e.preventDefault();
              handleAddNewType();
            }
          }}
        />
        <button
          type="button"
          onClick={handleAddNewType}
          className="px-3 py-1.5 bg-cyan-600 hover:bg-cyan-500 rounded text-xs text-white font-medium transition-colors"
        >
          Save
        </button>
        <button
          type="button"
          onClick={() => {
            setIsAddingNewType(false);
            setNewTypeInput('');
          }}
          className="px-3 py-1.5 text-xs text-gray-400 hover:text-white transition-colors"
        >
          Cancel
        </button>
      </div>
    ) : (
      <button
        type="button"
        onClick={() => setIsAddingNewType(true)}
        className="px-3 py-2 rounded-lg text-sm font-medium bg-white/5 text-cyan-400 border border-cyan-500/30 hover:bg-cyan-500/10 hover:border-cyan-500/50 transition-all flex items-center justify-center gap-1"
      >
        <span className="text-lg">+</span> Add Type
      </button>
    )}
  </div>
  <p className="text-xs text-gray-400">
    Selected: {formData.testTypes.length > 0 ? formData.testTypes.join(', ') : 'None'}
  </p>
</div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-4 pt-6 border-t border-white/10">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 rounded-lg bg-gray-500/20 text-gray-300 hover:bg-gray-500/30 border border-gray-500/30 hover:border-gray-500/50 transition-all">Cancel
            </button>
            <button
              type="submit"
              className="px-6 py-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 text-white hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105 font-semibold"
            >
              Add Client
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}