import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { TEST_TYPE_LABELS } from "./types";
import axios from 'axios';

const SERVICE_TYPES = ['Material Testing', 'Calibration', 'Both'];
const STATUSES = ['Pending', 'Ongoing', 'Completed', 'Cancelled'];
const REQUEST_FORMS = ['Signed', 'Waiting', 'N/A'];
const TEST_TYPES = ['FTIR', 'CN', 'CT', 'CTT', 'MO', 'HT', 'FT', 'TS', 'BT', 'RE', 'UC', 'FD', 'HP', 'O'];

// Helper to format date to YYYY-MM-DD
const formatDateForInput = (dateValue) => {
  if (!dateValue) return '';
  try {
    const date = new Date(dateValue);
    if (!isNaN(date.getTime())) {
      return date.toISOString().split('T')[0];
    }
  } catch (e) {
    return '';
  }
  return '';
};

export function AddClientModal({ isOpen, onClose, onAdd }) {
  const [setErrors] = useState({service: ""});
  const [categories, setCategories] = useState([
    'BatStateU College',
    'Private HEIs',
    'Industry',
    'Private Individual',
    'Senior High',
    'BatStateU IS',
  ]);

  useEffect(() => {
    axios.get('http://192.168.0.126:5000/categories')
      .then(res => {
        const saved = res.data.map(cat => cat.company);
        // Merge hardcoded + saved, avoid duplicates
        setCategories(prev => [...prev, ...saved.filter(s => !prev.includes(s))]);
      })
      .catch(err => console.error(err));
  }, [isOpen]); // refetch whenever modal opens

  const [isAdding, setIsAdding] = useState(false);
  const [newcat, setNewCat] = useState({ name: '', color: '#06b6d4' });

  const today = new Date().toISOString().split('T')[0];
  const handleDateChange = (field, value) => {
    if (value > today) {
      setFormData(prev => ({ ...prev, [field]: '' }));
    } else {
      setFormData(prev => ({ ...prev, [field]: value }));
    }
  }

  const [formData, setFormData] = useState({
    // Note: id, serviceNo, serviceRequestID should be auto-generated by backend
    
    // Client Information
    name: '',
    companyName: '',
    address: '',
    email: '',
    phone: '',
    
    // Service Details
    category: 'Industry',
    serviceType: 'Material Testing',
    status: 'Pending',
    progress: 0,
    
    // Dates
    dateRequested: '',
    dueDate: '',
    dateReleased: '',
    dateClaimed: '',
    testDate: '',
    releasedROA: '',
    
    // Documentation & Forms
    requestForm: 'Waiting',
    roaV: false,
    roa: false,
    ts: false,
    
    // Sample Information
    sampleNo: '',
    specimenNo: '',
    sampleCount: 0,
    sampleRangeStart: '',
    sampleRangeEnd: '',
    
    // Financial
    amount: 0,
    officialReceipt: false,
    
    // Test Types & Remarks
    testTypes: [],
    remarks: '',
  });
  
  const handleSubmit = (e) => {
    e.preventDefault();

    // Validation
    if (!formData.dateRequested) {
      alert("Date Requested is required");
      return;
    }

    if(!formData.roa && !formData.ts) {
      setErrors({service: "Please select!"});
      return;
    }
    
    if (new Date(formData.dateRequested) > new Date()) {  
      alert("Date Requested cannot be in the future");
      return;
    }
    
    // Transform data to match database schema
    const dataForBackend = {
      // Backend should auto-generate: id, serviceNo, serviceRequestID
      
      // Client Information
      name: formData.name.trim(),
      company: formData.companyName.trim(),
      address: formData.address.trim(),
      email: formData.email.trim().toLowerCase(),
      phone: formData.phone.replace(/\s/g, ''), // Remove formatting spaces
      
      // Service Details
      category: formData.category,
      serviceType: formData.serviceType,
      status: formData.status,
      progress: Number(formData.progress),
      
      // Dates (ensure YYYY-MM-DD format, or null if empty)
      dateRequested: formatDateForInput(formData.dateRequested) || null,
      startDate: formatDateForInput(formData.startDate) || null,
      dueDate: formatDateForInput(formData.dueDate) || null,
      dateReleased: formatDateForInput(formData.dateReleased) || null,
      dateClaimed: formatDateForInput(formData.dateClaimed) || null,
      testDate: formatDateForInput(formData.testDate) || null,
      releasedROA: formatDateForInput(formData.releasedROA) || null,
      
      // Documentation
      requestForm: formData.requestForm,
      roaV: formData.roaV,
      roa: formData.roa,
      ts: formData.ts,
      
      // Sample Information
      sampleNo1: formData.sampleRangeStart ? Number(formData.sampleRangeStart) : null,
      sampleNo2: formData.sampleRangeEnd ? Number(formData.sampleRangeEnd) : null,
      specimenNo: formData.specimenNo.trim() || null,
      sampleCount: Number(formData.sampleCount) || 0,
      
      // Financial
      amount: Number(formData.amount),
      officialReceipt: formData.officialReceipt,
      
      // Test Types (convert array to comma-separated string)
      testTypes: formData.testTypes.join(', '),
      
      // Additional
      remarks: formData.remarks.trim() || null,
    };
    
    // Debug: Log the data being sent
    console.log('=== DATA BEING SENT TO BACKEND ===');
    console.log('sampleNo1:', dataForBackend.sampleNo1, 'Type:', typeof dataForBackend.sampleNo1);
    console.log('sampleNo2:', dataForBackend.sampleNo2, 'Type:', typeof dataForBackend.sampleNo2);
    console.log('company:', dataForBackend.company);
    console.log('roa:', dataForBackend.roa);
    console.log('ts:', dataForBackend.ts);
    console.log('Full data:', dataForBackend);
    console.log('===================================');
    
    // Send to backend
    onAdd(dataForBackend);
    
    // Reset form
    setFormData({
      name: '',
      companyName: '',
      address: '',
      email: '',
      phone: '',
      category: 'Industry',
      serviceType: 'Material Testing',
      status: 'Pending',
      progress: 0,
      dateRequested: '',
      startDate: '',
      dueDate: '',
      dateReleased: '',
      dateClaimed: '',
      testDate: '',
      releasedROA: '',
      roaV: false,
      requestForm: 'Waiting',
      roa: false,
      ts: false,
      sampleNo: '',
      specimenNo: '',
      sampleCount: 0,
      sampleRangeStart: '',
      sampleRangeEnd: '',
      amount: 0,
      officialReceipt: false,
      testTypes: [],
      remarks: '',
    });
  };

  const toggleTestType = (type) => {
    setFormData(prev => ({
      ...prev,
      testTypes: prev.testTypes.includes(type)
        ? prev.testTypes.filter(t => t !== type)
        : [...prev.testTypes, type],
    }));
  };

  // Calculate sample count based on range
  const handleSampleRangeChange = (field, value) => {
    const newFormData = { ...formData, [field]: value };
    
    // Auto-calculate sample count if both start and end are provided
    if (field === 'sampleRangeStart' || field === 'sampleRangeEnd') {
      const start = field === 'sampleRangeStart' ? parseInt(value) : parseInt(formData.sampleRangeStart);
      const end = field === 'sampleRangeEnd' ? parseInt(value) : parseInt(formData.sampleRangeEnd);
      
      if (!isNaN(start) && !isNaN(end) && start > 0 && end >= start) {
        // Calculate: (end - start) + 1
        newFormData.sampleCount = (end - start) + 1;
      } else {
        newFormData.sampleCount = 0;
      }
    }
    
    setFormData(newFormData);
  };

  if (!isOpen) return null;
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl bg-gradient-to-br from-slate-900 to-slate-800 border border-white/10 shadow-2xl">
        <div className="sticky top-0 z-10 flex items-center justify-between p-6 border-b border-white/10 bg-slate-900/95 backdrop-blur-xl">
          <h2 className="text-2xl font-bold text-white">Add New Client</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-lg bg-red-500/20 text-red-300 hover:bg-red-500/30 border border-red-500/30 hover:border-red-500/50 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Client Info Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Client Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Client Name <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => {
                    const value = e.target.value;
                    const regex = /[^a-zA-Z.'()-\s]/g;
                    const onlyLetters = value.replace(regex, "");
                    setFormData({ ...formData, name: onlyLetters });
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="Enter client name"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Company Name <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  value={formData.companyName}
                  onChange={(e) => setFormData({ ...formData, companyName: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="Enter company name"
                />
              </div>
            </div>
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Address <span className="text-red-500">*</span></label>
                <input
                  type="text"
                  value={formData.address}
                  onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="Enter address"
                />
              </div>
            </div>
          </div>

          {/* Contact Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Contact Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Email <span className="text-red-500">*</span></label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="email@example.com"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Phone <span className="text-red-500">*</span></label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => {
                    const rawValue = e.target.value.replace(/\D/g, '');
                    const truncated = rawValue.slice(0, 11);
                    let formatted = truncated;
                    if (truncated.length > 4) {
                      formatted = `${truncated.slice(0, 4)} ${truncated.slice(4)}`;
                    }
                    if (truncated.length > 7) {
                      formatted = `${truncated.slice(0, 4)} ${truncated.slice(4, 7)} ${truncated.slice(7)}`;
                    }
                    setFormData({ ...formData, phone: formatted });
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="09XX XXX XXXX"
                />
              </div>
            </div>
          </div>
                
          {/* Service Details Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Service Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Category <span className="text-red-500">*</span></label>
                <select
                  required
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {categories.map((cat) => (
                    <option key={cat} value={cat} className="bg-slate-800">{cat}</option>
                  ))}
                </select>
                {!isAdding ? (
                  <button
                    type="button"
                    onClick={() => setIsAdding(true)}
                    className="mt-2 text-xs flex items-center gap-1 text-cyan-400 hover:text-cyan-300 transition-colors">
                    <span className="text-lg">+</span>Add New Category
                  </button>
                ) : (
                  <div className="mt-3 p-3 border border-white/10 rounded-lg bg-white/5 space-y-3">
                    <div className="flex gap-2 items-center">
                      <input
                        type="text"
                        placeholder="New category name"
                        value={newcat.name}
                        onChange={(e) => setNewCat({ ...newcat, name: e.target.value })}
                        className="flex-1 px-3 py-1.5 bg-slate-900 border border-white/20 rounded text-sm text-white focus:ring-1 focus:ring-cyan-500 outline-none"
                      />
                      <div className="relative group">
                        <input
                          type="color"
                          value={newcat.color}
                          onChange={(e) => setNewCat({ ...newcat, color: e.target.value })}
                          className="w-10 h-9 bg-transparent border-none cursor-pointer rounded overflow-hidden"
                        />
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <button
                        type="button"
                        onClick={() => setIsAdding(false)}
                        className="text-xs text-gray-400 hover:text-white transition-colors"
                      >
                        Cancel
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (!newcat.name.trim()) return;

                          // 1. Save the color mapping to localStorage before/during the backend call
                          const categoryName = newcat.name.trim();
                          const categoryColor = newcat.color; // This is the color from the <input type="color" />

                          const storedColors = JSON.parse(localStorage.getItem('customCategoryColors') || '{}');
                          storedColors[categoryName] = categoryColor;
                          localStorage.setItem('customCategoryColors', JSON.stringify(storedColors));

                          // 2. Existing axios call
                          axios.post('http://192.168.0.126:5000/categories', { name: categoryName })
                            .then(res => {
                              setCategories(prev => [...prev, categoryName]);
                              setFormData({ ...formData, category: categoryName });
                              setNewCat({ name: '', color: '#06b6d4' });
                              setIsAdding(false);
                              
                              // Optional: Force a refresh event so other open modals see the change
                              window.dispatchEvent(new Event('storage'));
                            })
                            .catch(err => {
                              console.error(err);
                              alert("Error saving category");
                            });
                        }}
                        className="text-xs bg-cyan-600 hover:bg-cyan-500 px-3 py-1.5 rounded text-white font-medium transition-colors"
                      >
                        Save Category
                      </button>
                    </div>
                  </div>
                )}
              </div>   
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Service Type <span className="text-red-500">*</span></label>
                <select
                  required
                  value={formData.serviceType}
                  onChange={(e) => setFormData({ ...formData, serviceType: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {SERVICE_TYPES.map((type) => (
                    <option key={type} value={type} className="bg-slate-800">{type}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Status <span className="text-red-500">*</span></label>
                <select
                  required
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {STATUSES.map((status) => (
                    <option key={status} value={status} className="bg-slate-800">{status}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* Progress and Dates */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Progress & Timeline</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Progress (%) <span className="text-red-500">*</span></label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  required
                  value={formData.progress ?? ''}
                  onChange={(e) => {
                    const val = e.target.value;
                    if (val === "") {
                      setFormData({ ...formData, progress: "" });
                      return;
                    }
                    const numValue = Number(val);
                    if (numValue > 100 || numValue < 0) {
                      setFormData({ ...formData, progress: "" });
                    } else {
                      setFormData({ ...formData, progress: numValue });
                    }
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="0"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Requested <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  required
                  value={formData.dateRequested}
                  max={today}                  
                  onChange={(e) => handleDateChange('dateRequested', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
                {(() => {
                  const dateValue = formData.dateRequested;
                  const year = dateValue ? parseInt(dateValue.split('-')[0]) : 0;
                  const isComplete = dateValue?.length === 10 && year > 1900;

                  if (isComplete) {
                    return (
                      <div className="mt-3 p-3 bg-white/5 border border-white/8 rounded-lg flex gap-8 animate-in fade-in zoom-in-95 duration-200">
                        <label className="flex items-center block text-md font-md text-gray-300">
                            Service Request Form<span className="text-red-500">*</span>
                        </label>
                        
                        <label className="flex items-center space-x-3 cursor-pointer group text-gray-300 hover:text-gray-300 transition-colors">
                          <input 
                            type="checkbox" 
                            checked={formData.roa} 
                            onChange={(e) => setFormData({ ...formData, roa: e.target.checked, ts: false })}
                            className="rounded border-gray-500 bg-transparent focus:ring-offset-0 focus:ring-0"
                          /> 
                          <span>ROA</span>
                        </label>

                        {/* TS Checkbox */}
                        <label className="flex items-center space-x-3 cursor-pointer group text-gray-300 hover:text-gray-300 transition-colors">
                          <input 
                            type="checkbox" 
                            checked={formData.ts} 
                            onChange={(e) => setFormData({ ...formData, ts: e.target.checked, roa: false })}
                            className="rounded border-gray-500 bg-transparent focus:ring-offset-0 focus:ring-0"
                          /> 
                          <span>TS</span>
                        </label>               
                      </div>
                    );
                  }
                  return null;
                })()}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Start Date <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  value={formData.startDate}
                  onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Due Date <span className="text-red-500">*</span></label>
                <input
                  type="date"
                  value={formData.dueDate}
                  onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Claimed</label>
                <input
                  type="date"
                  value={formData.dateClaimed}
                  max={today}
                  onChange={(e) => handleDateChange('dateClaimed', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date Released</label>
                <input
                  type="date"
                  value={formData.dateReleased}
                  max={today}
                  onChange={(e) => handleDateChange('dateReleased', e.target.value)}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
            </div>
          </div>

          {/* Request Form and Amount */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Documentation & Payment</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Request Form Status <span className="text-red-500">*</span></label>
                <select
                  value={formData.requestForm}
                  onChange={(e) => setFormData({ ...formData, requestForm: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                >
                  {REQUEST_FORMS.map((form) => (
                    <option key={form} value={form} className="bg-slate-800">{form}</option>
                  ))}
                </select>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Date of Test</label>
                <input
                  type="date"
                  value={formData.testDate || ''}
                  onChange={(e) => setFormData({ ...formData, testDate: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Released of ROA Date</label>
                <input
                  type="date"
                  value={formData.releasedROA || ''}
                  onChange={(e) => setFormData({ ...formData, releasedROA: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  style={{ colorScheme: 'dark' }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Report of Analysis</label>
                <div className="p-2.5 bg-white/5 border border-white/10 rounded-lg">
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      id="roaV"
                      checked={formData.roaV || false}
                      onChange={(e) => setFormData({ ...formData, roaV: e.target.checked })}
                      className="w-5 h-5 rounded bg-white/5 border border-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    />
                    <label htmlFor="roaV" className="text-sm font-medium text-green-300">ROA Available</label>
                  </div>
                </div> 
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Sample No.</label>
                <div className="flex items-center gap-2">
                  <input
                    type="number"
                    min="1"
                    value={formData.sampleRangeStart || ''}
                    onChange={(e) => handleSampleRangeChange('sampleRangeStart', e.target.value)}
                    className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    placeholder="10"
                  />
                  <span className="text-gray-300 font-medium">-</span>
                  <input
                    type="number"
                    min="1"
                    value={formData.sampleRangeEnd || ''}
                    onChange={(e) => handleSampleRangeChange('sampleRangeEnd', e.target.value)}
                    className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    placeholder="15"
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Specimen No.</label>
                <input
                  type="text"
                  value={formData.specimenNo || ''}
                  onChange={(e) => setFormData({ ...formData, specimenNo: e.target.value })}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="e.g., SP-001"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Sample Count</label>
                <div className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white">
                  {formData.sampleCount > 0 ? formData.sampleCount : '0'}
                </div>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Amount (₱) <span className="text-red-500">*</span></label>
                <input
                  type="number"
                  min="0"
                  required
                  value={formData.amount ?? ''}
                  onChange={(e) => {
                    const val = e.target.value;
                    if (val === "") {
                      setFormData({ ...formData, amount: "" });
                      return;
                    }
                    const numValue = Number(val);
                    if (numValue < 0) {
                      setFormData({ ...formData, amount: "" });
                    } else {
                      setFormData({ ...formData, amount: numValue });
                    }
                  }}
                  className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                  placeholder="0"
                />
              </div>
              <div> 
                <label className="block text-sm font-medium text-gray-300 mb-2">Official Receipt</label>
                <div className="p-2.5 bg-white/5 border border-white/10 rounded-lg">
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      id="officialReceipt"
                      checked={formData.officialReceipt || false}
                      onChange={(e) => setFormData({ ...formData, officialReceipt: e.target.checked })}
                      className="w-5 h-5 rounded bg-white/5 border border-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                    />
                    <label htmlFor="officialReceipt" className="text-sm font-medium text-green-300">Receipt Available</label>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Remarks</label>
              <textarea
                value={formData.remarks || ''}
                onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                className="w-full px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
                placeholder="Additional notes or remarks"
                rows={3}
              />
            </div>
          </div>

          {/* Test Types */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-cyan-300 border-b border-cyan-500/30 pb-2">Test Types</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-2">
              {TEST_TYPES.map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => toggleTestType(type)}
                  className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${
                    formData.testTypes.includes(type)
                      ? 'bg-gradient-to-r from-pink-500 to-purple-600 text-white shadow-lg shadow-pink-500/50 border border-pink-500'
                      : 'bg-white/5 text-gray-300 border border-white/10 hover:bg-white/10'
                  }`}
                  title={TEST_TYPE_LABELS[type]}
                >
                  {type}
                </button>
              ))}
            </div>
            <p className="text-xs text-gray-400">Selected: {formData.testTypes.length > 0 ? formData.testTypes.join(', ') : 'None'}</p>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-4 pt-6 border-t border-white/10">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 rounded-lg bg-gray-500/20 text-gray-300 hover:bg-gray-500/30 border border-gray-500/30 hover:border-gray-500/50 transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-6 py-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 text-white hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105 font-semibold"
            >
              Add Client
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}