export const TEST_TYPE_LABELS = {
  FTIR: 'FTIR Analysis',
  CN: 'Centrifuge, Non-Refrigerated',
  CT: 'Compressive Test',
  CTT: 'Coating Thickness Test',
  MO: 'Moisture Test',
  HT: 'Hardness Test',
  FT: 'Flexural Test',
  TS: 'Tensile Strength',
  BT: 'Bending Test',
  RE: 'Rotary Evaporator',
  UC: 'Ultracentrifuge',
  FD: 'Freeze Dryer',
  HP: 'Heating Plate and Magnetic Stirring',
  O: 'Other',
};
